### ISSUE TITLE
Double Checks of stick probability

### ISSUE THREAD

**Issue by joshuacoles** [cm2435/diffusion-limited-aggregation#1]
When performing stick calculations you perform two probabilistic checks for a successful stick. This can be seen in the following two code sections:

https://github.com/cm2435/diffusion-limited-aggregation/blob/bafd073d6f1a2b80acf82f7efd5121576b5563ba/src/DLASystem.cpp#L208-L220

https://github.com/cm2435/diffusion-limited-aggregation/blob/bafd073d6f1a2b80acf82f7efd5121576b5563ba/src/DLASystem.cpp#L233-L252

Both approaches are valid, either inserting the probability check after we have confirmed we are in the correct location (the first code block), or for each possible stick (up, down, left, right). However the inclusion of both is an error giving you a stick probability $p_{err} \sim p^2$.

We should ask the lecturers which behaviour is correct, I chose the former but thinking about it the latter may be more "correct".

**Comment by cm2435** [comment]
Absolutely correct, good spot my man

**Comment by cm2435** [comment]
#2 Fixes this, after some debate about what function to remove sticking probability from with @joshuacoles (they in fact *do* differ in behaviour) this has been PR'ed and merged
